### ISSUE TITLE
New CMCD key to drive CDN log stream sampling

### ISSUE THREAD

**Issue by zen-tek** [cta-wave/common-media-server-data#10]
A suggestion was made in the SVA QoE working group that it might make sense to add a CMCD key that indicates whether or not a cache log line should be included in log streaming to CDN customers. This enables player-driven CDN log sampling for synchronized, whole session sampling. In other words, if a play session is in a sample set for player event log collection, the player could inform the CDN that cache log lines supporting that session should also be streamed to customer -configured end points. 

There was some debate about whether or not signaling a CDN to include cache log lines for log streaming fits with the intent around CMCD as a communication mechanism. However, for practical reasons (industry traction, ease of integration), CMCD might be a good fit regardless.

We can get into specifics once we align on whether or not CMCD is the right place for this signal to live.

**Comment by wilaw** [comment]
@Zen-tek - should this be filed against the [CMCD repo](https://github.com/cta-wave/common-media-client-data/issues) instead of CMSD ?

**Comment by zen-tek** [comment]
Closing this issue. It has been moved over to the CMCD repo.
