### ISSUE TITLE
Toggle on/off sending of CMSD data

### ISSUE THREAD

**Issue by pankaj-giter** [cta-wave/common-media-server-data#12]
Ask: A flag to toggle on/off the sending of CMSD data generated by upstream and sent to downstream systems.

Rationale: The capability to enable a specific functionality, in this case CMSD data, is an important dev-ops aspect of any organization. For CMSD, the data can be generated by all systems upstream of the player. By allowing the receiver to control if the sender can/should send the CMSD data in responses is a desirable feature. This will give flexibility in the face of bugs in generation and processing of the CMSD data.

Solution Proposal:
1. The client can send a flag (http request/query param) indicating whether it is willing to accept CMSD data in the response.
2. The flag must be honored by the server and when set to 'off', the server must not send any CMSD response. 
3. A toggle flag sent by a client and received by a server is only applicable between these 2 systems. It must not impact the CMSD functionality upstream of 'this' server. Example: with a toggle off between player and edge, this flag has no bearing on the communication between edge and its cache parent and cache parent and the origin.
4. Default value of this flag is 'on', i.e. CMSD data will be sent in response.
5. This flag could be named 'cmsd-toggle'
6. Additionally, when versioning comes into play a flag such as 'cmsd-v1-toggle' could be used.

**Comment by wilaw** [comment]
Meeting 3/7/22 - noted that 
1. Flag should be a key within CMCD, since it is a request flag. 
2. Clients could more simply not trust the returned CMSD data, versus setting a flag to tell the server not to send it. The use-case is the server sending malformed or erroneous data, which is likely to be an edge case. 
3. CDNs will most likely have settings to toggle CMSD on/off.

**Comment by wilaw** [comment]
Opened request against CMCD https://github.com/cta-wave/common-media-client-data/issues/82.
