### ISSUE TITLE
Clarification around pre caching

### ISSUE THREAD

**Issue by kevleyski** [cta-wave/common-media-server-data#16]
(again feedback/concern from the CMSD introductory presentation)

Question/Comment: There could be some significant charges due to pre-caching content - e.g. pulling all variants, init + first segment and so on?

Answer: pre caching is of course optional, but shouldn’t include all variants, only the ones your player suggests it might need

**Comment by wilaw** [comment]
Your answer is correct. Prefetching (precaching) is optionally implemented by the CDN. Some CDNs charge additional for prefetched content (by charging for midgress traffic), other only charge for egress traffic. Given that the prefetched content is also cached, it only represents an additional charge if it is never requested. So if there is a sufficiently large population of players pulling from an edge, prefetching all bitrates would happen naturally. None-the-less, players are not recommended to pull all bitrates to the edge. A reasonable strategy would be to always pull the lowest bitrate to the edge. This provides a fast bail-out option for players suffering throughput loss , while minimizing midgress traffic abd edge cache space.
