### ISSUE TITLE
Naming of the spec

### ISSUE THREAD

**Issue by acbegen** [cta-wave/common-media-server-data#4]
I guess it is too late to change the name for CMCD (and CMSD) but could we at least ease the pain a bit by using:
1) Common Media-Client Data (CMCD)
2) Common Media-Server Data (CMSD)

Without a hyphen, we read this as "common media" client/server data and that is not the intention. I am open to other suggestions, too.

**Comment by wilaw** [comment]
Small consensus in favor of leaving as is at 6/21 call.
