### ISSUE TITLE
Inclusion of network transport related information

### ISSUE THREAD

**Issue by piersoh** [cta-wave/common-media-server-data#5]
The current CMSD spec contains an estimated throughput (`etp`) entry. This information, and other related metrics (e.g. RTT, MSS, etc), could be obtained directly from the edge proxy transport layer as we detailed in our "Transport-Info header" Internet draft:
https://datatracker.ietf.org/doc/html/draft-ohanlon-transport-info-header

Such transport metrics are readily available at a proxy/edge node from the transport layer stack - in the case of TCP these are available from the `tcp_info` data structure which is accessible from a number of web servers/proxies (e.g. Nginx [tcpinfo_rtt](https://nginx.org/en/docs/http/ngx_http_core_module.html#variables), VCL's [tcp-info](https://developer.fastly.com/reference/vcl/variables/client-connection/client-socket-tcp-info/)). For other transport protocols (e.g. QUIC) similar information can also be obtained (e.g. Facebook's mvfst [TransportInfo](https://github.com/facebookincubator/mvfst/blob/38c903ba2f6377f5d213f096505d8b8d773cc0a9/quic/api/QuicTransportBase.cpp#L523), VCL's [quic.rtt](https://developer.fastly.com/reference/vcl/variables/client-connection/quic-rtt-smoothed/))

The draft also suggests structured header formatting of the information with inclusion of an id and timestamping of entries so their origin and timeliness can be ascertained which may be of use in the CMSD spec.

Specific suggestions:
- The 'etp' entry could be calculated using the transport-info metrics on the edge server.
  - Qualify the source of the estimate to where the information originated e.g. transport-info or some other source.
  - Provide a confidence measure of the estimate
  - Adding a timestamp to the estimate
- Such entries may be best provided by a proxy/edge node replacing any existing estimate since the final(edge) estimate is likely to be the most relevant to the client
- Consideration of including additional metrics e.g. RTT, MSS

**Comment by wilaw** [comment]
Could confidence be expressed as buckets - low, medium, high? 
RTT would be useful for many web clients. 
Timestamp could apply to all dynamic entries. Time window of validity is a separate question.

**Comment by piersoh** [comment]
With respect to representation of any additional parameters we can just use the existing [`sf-list`](https://www.rfc-editor.org/rfc/rfc8941.html#name-lists) type we're using the spec (I added a clarification there) - as is used in the [Transport-Info draft](https://bbc.github.io/draft-ohanlon-transport-info-header/draft-ohanlon-transport-info-header.html); So each `list-member` can consist of one or more key/value pairs separated by `;`, with the `list-members` being separated by a `,` e.g.

     CMSD-Dynamic: etp=1000;src=ti;ts="2019-08-30T14:56:08.069Z", mb=3000

**Comment by alficles** [comment]
We should have a conversation about whether the Transport-Info data should be incorporated into CMSD or whether it really does just make sense as it's own header.

**Comment by piersoh** [comment]
A related draft on the "Delivery Rate Estimation" - which is generic algorithm for a transport protocol sender to estimate the current delivery rate of its data: https://datatracker.ietf.org/doc/html/draft-cheng-iccrg-delivery-rate-estimation

**Comment by wilaw** [comment]
We shall incorporate two keys directly from Transport-Info  - ETP and RTT - as these are directly understandable and actionable by most players. Distributors can add Transport-Info headers in addition to the CMSD headers for cases in which more detailed transport data is known and in which clients understand how to use this data. Servers have several different options for estimating ETP depending on protocol, mobile-network collaboration etc.
