### ISSUE TITLE
CMCD/CMSD talk at ACM/IRTF ANRW 2021

### ISSUE THREAD

**Issue by acbegen** [cta-wave/common-media-server-data#7]
[This](https://www.linkedin.com/pulse/manus-manum-lavat-ali-c-begen) is the text version of an invited talk I will be giving today at [ACM/IRTF ANRW 2021](https://irtf.org/anrw/2021/). The video and slides will be posted [here](https://irtf.org/anrw/2021/program.html). The [companion short paper](https://dl.acm.org/doi/10.1145/3472305.3472886) is already in ACM Digital library. There will be a short panel/Q&A following the talk.

**Comment by wilaw** [comment]
Thanks for sharing.
