### ISSUE TITLE
SEO: It's hard to find this GitHub project when searching the web for 'CMSD'

### ISSUE THREAD

**Issue by icbaker** [cta-wave/common-media-server-data#8]
I remember this project by its acronymn rather than the full name - but when searching on Google for 'cmsd' it doesn't show up. 'cmsd cta' doesn't really help either. 'cmsd cta wave' gets me a link to the [parent GitHub org](https://github.com/cta-wave) (but it's flagged as missing 'cmsd'):
![Screenshot 2021-08-02 at 17 03 25](https://user-images.githubusercontent.com/1279752/127890872-5cf70c8d-54cb-47f5-84da-275f2419be9f.png)

I wonder if some more uses of the acronymn in README.md might help search engines associate the acronymn with this page? 

(this is obviously not a major deal - just flagging as a minor thing)

**Comment by wilaw** [comment]
@Ali - add some SEO text to that search engines with index us via CMSD

**Comment by acbegen** [comment]
Here is the suggested text for the readme.md:

Editors:
- Will Law - Akamai
- Ali C. Begen - Comcast / Ozyegin University
- Josh Evans - Datazoom

This is the repository to collect discussion and feedback on the Common Media Server Data (CMSD) proposal, which is developed as a companion to the [Common Media Client Data (CMCD) standard (CTA-5004)](https://shop.cta.tech/products/web-application-video-ecosystem-common-media-client-data-cta-5004). The current CMSD draft document can be accessed [here](https://docs.google.com/document/d/1BlTHfbF2VGSlA4vLx1fMssWqiGWYuzhmTfQ8VeyxF8g). Feel free to open issues or comment on the draft directly.

Any contribution made to the issues of this repository that results in a “shall” requirement pointing to an essential patent will require the company or individual holding the IPR to submit a [Patent Holder Statement form](https://standards.cta.tech/kwspub/rules/CTA-EP-23-T-IP-Proffer.pdf). Contributors are obliged to disclose to the working group any knowledge they may have of existing essential patents (or an intent to patent items whenever appropriate) affecting the work covered by this repository.

Note that CTA is not responsible for identifying any patents for which a license may be required by a CTA document, nor for conducting inquiries into the legal validity or scope of those patents that are brought to its attention. For further IPR information, see Section 15 of [EP-23](https://standards.cta.tech/kwspub/rules/CTA-EP-23-T.pdf).

**Comment by acbegen** [comment]
Implemented the changes now.
